### ISSUE TITLE
finished but unsuccessful running with genome and HMM file

### ISSUE THREAD

**Issue by thkuo** [philippmuench/eden#3] opened 2017-05-24 14:17 UTC
I was using Eden with 398 genome sequences and a HMM file, which includes 2198 profiles generated by my pre-computed alignment files. Though the portal gave a massage of finished job, the outcome couldn't be seen with "visualize job" function (i.e. not listed under "Select run"). The log can be seen below:
```
type	time	message
internal		update ui
status	13:46:52	finished
status	13:46:52	movind data
status	13:46:52	results exported
status	13:46:52	create consensus sequence on pooled samples
status	13:46:52	get alignment informations on pooled samples
status	13:46:52	calculate ratio on pooled samples
status	13:46:52	generating trees on pooled samples
status	13:46:52	generate codon alignment on pooled samples
status	13:46:52	generate alignments on pooled samples
error	13:46:52	cannot move folder
error	13:46:52	cannot move folder
status	13:46:52	checking hits on pooled samples
error	13:46:52	error when moving files
error	13:46:52	error when moving files
status	13:46:52	extract hits on pooled samples
status	13:46:51	running eden.sh
error	13:46:51	cannot start check procedure, error code: 100
status	13:46:51	generate ORF table
status	13:46:51	annotate ORFs
status	13:46:39	rewrite fasta headers
status	12:36:23	run prodigal
status	12:36:23	running check.sh
status	12:36:23	start process
```
Can any solution be suggested?

**Comment by philippmuench** [comment] 2017-06-06 12:50
Seems that the problem is that you provide nucleic HMM models instead of amino acid HMM models, currently the sequences will be extracted based on the .faa files. This information is missing in the manual/github description, so I will add this and also add it to the check procedure on file upload. 

Can you regenerate the .hmm models using the `hmmbuild` command for amino acids? 

The header of the .hmm model should be like in the example file on https://github.com/philippmuench/eden/blob/master/sample_files/gene_families.hmm

**Comment by philippmuench** [comment] 2017-06-19 12:09
There was also a error when uploading `.faa` files, this shoud be fixed now, please update to the newest version via `sudo docker pull philippmuench/eden`

**Closed as completed by philippmuench** 2017-06-19 12:09 UTC
